[workspace]
resolver = "2"
members = [
  "standalone",
  "lib",
]
default-members = ["standalone"]

[workspace.dependencies]
image = { version = "0.24.1", default-features = false, features = ["png", "hdr"] }
glam = "0.20.2"
wgpu = "0.18.0"

[profile.dev]
opt-level = 1
