[package]
name = "albedo-pathtracer"
version = "0.1.0"
authors = ["David Peicho <david.peicho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = {version = "0.23", default-features = false, features = ["hdr"]}
winit = { version = "0.24", features = ["web-sys"] }
enumflags2 = "0.7.1"
wgpu = "0.7.0"
glam = "0.11.2"
gltf = "0.15.2"
pollster = "0.2"
albedo_backend = { path = "../../albedo/albedo/crates/albedo_backend", version = "0.0.1" }
albedo_rtx = { path = "../../albedo/albedo/crates/albedo_rtx", version = "0.0.1" }
