[package]
name = "albedo-pathtracer"
version = "0.1.0"
authors = ["David Peicho <david.peicho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
albedo_rtx = { path = "../../albedo/albedo/crates/albedo_rtx", version = "0.0.1" }
